### ISSUE TITLE
按照你的方法，好像我自己写的代码注入不了

### ISSUE THREAD

**Issue by PikachuCN** [a312586670/processClientDemo#2]
我按照您的教程，写了3个程序，一个目标程序，一个HookDll，
这2个我测试已经没问题，我用您的DEMO，用我的HookDll，可以成功注入我的目标程序。

问题是

我使用FastWin32 进行注入时，我复制您的代码在我的winfrom里面无法成功注入。我用您的DEMO注入我的DLL则成功。

我对比过代码，已经几乎一模一样，差别就只有您使用wpf，我用winfrom。能否给与一个解决方向？

**Comment by e-jlion** [comment]
这个跟wpf 和winfrom 没关系，你检查下你的代码，适当的打一些日志试下
